spring:
  mvc:
    servlet:
      path: /api/v1
    multipart:
      max-image-size: 5MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: user
  secretKey: password
  bucketName: corpbucket

scheduled:
  removeExpiredAdsCron: "0 0 3 * * ?"