app:
  post-service:
    scheduledPostPublisher:
      butch: 100

spring:
  mvc:
    servlet:
      path: /api/v1
    multipart:
      max-image-size: 5MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        post_view: post_view_channel
        comment: comment-event-channel
        like: like-event-channel

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: user
  secretKey: password
  bucketName: corpbucket

text-gears:
  baseUrl: "https://textgears-textgears-v1.p.rapidapi.com/correct"
  xRapidKey: "1ec6bc6704mshd100f80998702b3p1438c7jsncbe0e6b62b30"
  xRapidHost: "textgears-textgears-v1.p.rapidapi.com"
  contentType: "application/x-www-form-urlencoded"

async:
  publishScheduledPosts:
    executor-name: scheduledPostPublish
    corePoolSize: 5
    maxPoolSize: 30
    queueCapacity: 100

scheduled:
  removeExpiredAdsCron: "0 0 3 * * ?"
  scheduledPostPublisher: "0 * * * * *"